### ISSUE TITLE
Allow terrains to be marked as difficult terrain (which applies an active effect halving the speed)

### ISSUE THREAD

**Issue by rapus95** [caewok/fvtt-terrain-mapper#11]
As Enhanced Terrain Layer won't be updated for v11 there's a hole to be filled. And this module seems to be just the right place for it.

**Comment by GhostwheelX** [comment]
Very much agree.

**Comment by caewok** [comment]
I have a [PR](https://github.com/manuelVo/foundryvtt-drag-ruler/pull/306) for Drag Ruler so the ruler can tell when movement is limited by terrain.

I don't love the idea of simply marking terrain as "difficult" because that is very system-specific. You can already set up terrain to limit movement of the affected token.

**Comment by GhostwheelX** [comment]
How does terrain "limit" movement? It's not easy to see when dragging tokens without the guideline from Drag Ruler 🤔

**Comment by caewok** [comment]
You can limit any move attribute by setting the active effect to modify the relevant move attribute. For example, in dnd5e, this would make the terrain 2x difficulty, in that any affected token would have their movement cut in half:

<img width="583" alt="Screenshot 2023-12-21 at 7 17 35 PM" src="https://github.com/caewok/fvtt-terrain-mapper/assets/1267134/bd051341-1bae-4c2d-aa00-9c89f842b9f7">

This is admittedly more complicated than enabling a checkbox for "difficult" terrain, but comes with some significant advantages:
- It is system independent. So long as the system uses active effects, you can modify an actor's move attribute.
- It does not predetermine which move attribute(s) you want to affect. For dnd5e, you might want to make terrain difficult for climbing, walking, or swimming. Or all three. 
- It does not predetermine the multiplier.
- It works well with actors that have different speeds or other active effects applied. 

Ultimately, however, a few "easy buttons" might be nice for commonly used system defaults. Like half movement for walking in dnd5e.

**Comment by rapus95** [comment]
does that interact correctly with only fractions of the path being difficult terrain? that is, correct upscaling of the remaining movement (*2)? Btw where can I even see the remaining movement? Seeing half the move speed in the char sheet won't really help here and instead feel misleading 🙈

**Comment by rapus95** [comment]
Generally speaking, I support all of your points that active effects are the better fit for implementing it.
In that case the proposal would need to be changed to "implement a toggle to automatically apply an active effect which halves the speed"

**Comment by caewok** [comment]
Try in v12. I added some default terrains, including difficult terrain, for dnd5e.
