### ISSUE TITLE
Broken link on the Foundry page

### ISSUE THREAD

**Issue by steveculshaw** [caewok/fvtt-terrain-mapper#13]
There is a broken link on the Foundry page ...

<img width="414" alt="image" src="https://github.com/caewok/fvtt-terrain-mapper/assets/64320/a8d8823b-41ad-4cf0-a9e5-ba1baced8118">

**Comment by caewok** [comment]
Thanks! Apparently it works in Safari but not Chrome. Hopefully I can stumble upon a solution.

**Comment by steveculshaw** [comment]
@caewok I think the issue is the video is in "mov" format ... seems Chrome and Edge don't support it 

[stackoverflow](https://stackoverflow.com/questions/57060193/browser-support-for-mov-video)
