### ISSUE TITLE
Have train be part of the scene data

### ISSUE THREAD

**Issue by BladeFireLight** [caewok/fvtt-terrain-mapper#19]
Train data is lost when switching scenes. requiring an export from every scene.

**Comment by caewok** [comment]
I assume you mean terrain data. And I don't understand what you mean by it being lost. At least on my version, terrain data persists across scenes in two respects: (1) the scene map stores the terrain painted on it, even when reloading or switching back and forth; (2) the terrain book holding the various terrains persists when reloading or switching scenes.

**Comment by caewok** [comment]
Closing as not replicable
