### ISSUE TITLE
No icon and error in console

### ISSUE THREAD

**Issue by YenBenGrey** [caewok/fvtt-terrain-mapper#2]
Hello there, 

I have installed it and turned it on, however there is no book icon, and I get this in my console.

I have left out the first part as that is my host domain for my game. 
![Screenshot 2023-10-10 at 20 56 50](https://github.com/caewok/fvtt-terrain-mapper/assets/98095856/5e26d88e-3bc1-45d2-91c4-6a0acac9b40e)

**Comment by caewok** [comment]
Thanks! Try it in v0.0.2. Your system must be case-sensitive, and there is a typo in the import that was not causing an error on my end.
