### ISSUE TITLE
activeTerrainsAt fails with error, FVTT Set::map is not applicable here

### ISSUE THREAD

**Issue by AterIgnis** [caewok/fvtt-terrain-mapper#21]
https://github.com/caewok/fvtt-terrain-mapper/blob/53a8b7c9aa5441235fef1bd5a3bb242dd87d1dcf/scripts/TerrainLayer.js#L349

Description:
FVTT Set::map function ensures initial and resulting sets are of same size, but it might not be correct with mapping, so error arises.

How to reproduce:
- Add terrain to scene layer
- Add tile with same terrain in configuration
- Try moving in overlapping area / do something else to invoke terrain.activeTerrainsAt(...)

Solution:
Call to .map should be replaced with manual transform, something like
```
const terrains = new Set();
this.terrainLevelsAt(location)
  .filter(t => t.activeAt(elevation, location))
  .forEach(t => terrains.add(t.terrain))
return terrains
```

**Comment by caewok** [comment]
Thanks! Should be fixed in v0.1.1.
