### ISSUE TITLE
Players can't see or interact with the terrain - Shadow of the Demon Lord rules

### ISSUE THREAD

**Issue by DM12345Z** [caewok/fvtt-terrain-mapper#23]
Hi, I have the terrain setup on the map and I walk the token through it on the GMs account.  Everything applies and is removed as the token moves through the terrain.  When I have one of my players try it, or i log in on one of their accounts it doesn't work.  When they choose to view the terrain by selecting the terrain layer icon they also do not see it.  Its like its doesn't exist on the players side.  Any help would be appreciated.  I'm using the shadow of the demon lord rule set.  Thanks

**Comment by caewok** [comment]
Try in v12 once the system is updated.
