### ISSUE TITLE
Console Error after Uninstall

### ISSUE THREAD

**Issue by Armandeus66** [caewok/fvtt-terrain-mapper#24]
I unstalled this module after realizing that PF2E is unsupported.

However, on loading Foundry, I get this console error:

```
HEAD https://(my URL)/modules/terrainmapper/module.json 404 (Not Found)
fetchWithTimeout    @    commons.js:13656
srcExists    @    foundry.js:29571
(anonymous)    @    terrainHelper.js:5
```

What can I do to stop this error from appearing?

**Comment by caewok** [comment]
No idea, sorry. Did you uninstall the module by going to modules in Foundry and right-clicking and then uninstalling?
