### ISSUE TITLE
Token movement does not trigger effect

### ISSUE THREAD

**Issue by ChaosRiderGustaph** [caewok/fvtt-terrain-mapper#25]
Token movement in terrain triggers the auto-terrain dialog but does not apply the effect to the triggering token.

Terrain effect is set to "Transfer to actor on item equip" but doesn't show up on the effects page of the token in said terrain.

Using latest 5e system

edit: Auto terrain is also enabled in options

**Comment by Randomisation** [comment]
I have the same issue

**Comment by caewok** [comment]
Is this still happening? Because I am testing v0.1.5 in Foundry v11, dnd5e 3.2.0, and it is working for me. Hoping the v0.1.5 release fixed this.

I added a wiki page that you might be able to use to share exported terrains: 
https://github.com/caewok/fvtt-terrain-mapper/wiki/Terrains
