### ISSUE TITLE
Error when moving a token while using Terrain Mapper and Elevation Ruler

### ISSUE THREAD

**Issue by SecretSquirrel77** [caewok/fvtt-terrain-mapper#27]
Hello!
I'm testing V12 on a fresh install. Elevation Ruler + Terrain Mapper is an amazing combo!
With both mods enabled (no other mods except libwrapper and socketlib), I get the following error whenever I moke any token. 
![image](https://github.com/caewok/fvtt-terrain-mapper/assets/77705375/59fdb863-f034-47d8-93fd-4e720df2b8f2)
I can't tell which mod has the issue, only that they both work without any issues on their own. Together, I get this error and the ruler function will not enable.
Terrain Mapper 0.3.1
Elevation Ruler 0.9.4
Foundry V12 latest build

**Comment by Nolat** [comment]
I've got the same error when using both modules

**Comment by caewok** [comment]
Thanks. Should be addressed in Terrain Mapper v0.3.2 along with Elevation Ruler v0.9.5.

**Comment by Nolat** [comment]
The error seems to have been fixed, but when a token passes over a difficult terrain region the ruler doesn't indicate anything special. The cost of a square remains the same and is not doubled.
