### ISSUE TITLE
[Feature] Option to set the elevation only if the token's elevation is lower

### ISSUE THREAD

**Issue by Nolat** [caewok/fvtt-terrain-mapper#28]
It would be useful to have an option allowing the elevation to be applied only if the token's elevation is lower.

For example, in the case of a token that can fly, is 30ft high and passes over a region that is 5ft high. It would be logical for its elevation not to be affected.

**Comment by caewok** [comment]
If the region is 5' high, then it will not affect a token that is 30' high. You do need to set the maximum height of the region for that to be true, however.

**Comment by AlexisArcs** [comment]
Thanks, it works to set a maximum elevation, I hadn't thought of that!

**Comment by Nolat** [comment]
Thanks, it works to set a maximum elevation, I hadn't thought of that!
