### ISSUE TITLE
I click on the book token and nothing happens....

### ISSUE THREAD

**Issue by YenBenGrey** [caewok/fvtt-terrain-mapper#3]
.....however over in the console this is what is shows. 

I am sorry I am no coder, so all I can do is feedback from a laymans point of view. Something also popped up in console when the world loaded too, I will add that screenshot first. 

![Screenshot 2023-10-10 at 21 23 52](https://github.com/caewok/fvtt-terrain-mapper/assets/98095856/95c16b71-f3e7-4058-b58b-44fb18ea0533)

And then this when I clicked on the book.
![Screenshot 2023-10-10 at 21 21 18](https://github.com/caewok/fvtt-terrain-mapper/assets/98095856/03f47204-6d28-4ba7-bfa0-c208db51c958)

**Comment by LukasPrism** [comment]
FWIW I'm having the same error/experience

**Comment by caewok** [comment]
I just released an update that should hopefully address this. Please let me know if it doesn't! Thanks!
