### ISSUE TITLE
Scene Background elevation should be a float

### ISSUE THREAD

**Issue by Nolat** [caewok/fvtt-terrain-mapper#33]
<img width="543" alt="image" src="https://github.com/caewok/fvtt-terrain-mapper/assets/22156783/10ec87c7-cee5-4e30-b851-685af2f20c5e">

As French players, we use the metric system. So instead of 5ft we have 1.5m, but currently the input value must be an integer.

**Comment by caewok** [comment]
Fixed in v0.4.0.
