### ISSUE TITLE
PF2e maps won't load with the latest update

### ISSUE THREAD

**Issue by Pyroman2xxx** [caewok/fvtt-terrain-mapper#36]
Foundry version v12.330
PF2e version 6.2.1

After installing version 0.4.0 none of the maps in my campaign will load and I get errors similar to this for each map:

> Error: Failed drawing interface canvas group: "refreshTerrainMapperMesh" is not defined as a supported RenderFlag option.. "refreshTerrainMapperMesh" is not defined as a supported RenderFlag option.
>     at Hooks.onError (foundry.js:654:24)
>     at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
>     at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
>     at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
>     at #draw (foundry.js:25053:15)
>     at async Canvas.draw (foundry.js:24937:5)
>     at async ScenePF2e.view (foundry.js:21358:7)
>     at async Game.initializeCanvas (foundry.js:9270:20)
>     at async Game.setupGame (foundry.js:9094:5)
>     at async Game._initializeGameView (foundry.js:10431:5)
>     at async Game.initialize (foundry.js:8994:5)

When I disable Terrain Mapper module everything loads again.

**Comment by redericd** [comment]
Seconding; I started getting this sort of error in my PF2e campaign until disabling Terrain Mapper.
FVTT v12.330
PF2e v6.2.1
Terrain Mapper 0.4.0

**Comment by Arkensald** [comment]
If it helps, I found a fix for this, but it involves disabling the terrain mapper module, then deleting all of the regions you currently have in your world, then re-enabling the module. Once re-enabled the issue doesn't seem to reoccur.

**Comment by xKillerbees** [comment]
Confirmed the update broke several of my scenes with any regions set. Disabling terrain mapper allowed me to continue using those scenes.

**Comment by Cronock92** [comment]
> Confirmed the update broke several of my scenes with any regions set. Disabling terrain mapper allowed me to continue using those scenes.

Second. 
FVTT v12.331
PF2e v6.2.3
Terrain Mapper 0.4.0

**Comment by Kronos25** [comment]
Also happening with me - the current version of the module also makes regions invisible and if you try to reload the scene/game you'll get the error OP posted and be locked out of this scene until you disable the module.

**Comment by caewok** [comment]
Should be fixed in v0.4.1.
