### ISSUE TITLE
Incorrectly displayed height in players view

### ISSUE THREAD

**Issue by Aqwyr** [caewok/fvtt-terrain-mapper#38]
Hello, I ran into a problem that the height of the terrain when moving tokens by players to the area is displayed incorrectly: where it should be +5, it display +10, where should be +10, there is +5. It also doesnt work for players to switch to heights by moving the keys or wasd - changes are simply not taken. But if you do all the same things for the dm, everything works as it should. How can I solve this?

**Comment by caewok** [comment]
I think this is fixed in v0.4.1 but let me know if it isn't!
