### ISSUE TITLE
Token cannot go down stairs

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-terrain-mapper#44]
((Sorry for the double ticket, wasn't sure if this was an elevation ruler problem or a terrain mapper problem))

As seen in the gif. A token can properly go up the ramp (stairs) and it stops at the top to reset vision properly. However, when going back down the ramp, even though the token stops, the elevation of the token is no longer modified by the ramp region. 

![Ramp down missing!](https://github.com/user-attachments/assets/86d17353-77da-4e98-9a76-57986236fe10)

Foundry: 12.331
System: 3.3.1
Elevation Ruler: 0.10.4
Levels: 5.3.0
Terrain Mapper 0.4.1

![image](https://github.com/user-attachments/assets/d2de050d-d52d-4346-88fa-9fdefb9b272a)

![image](https://github.com/user-attachments/assets/6ef02d1e-5f7b-4483-8cf3-84fd8085b6e5)

![image](https://github.com/user-attachments/assets/5af6e1ef-a775-4e91-b56b-b4433c15266a)

![image](https://github.com/user-attachments/assets/c6436794-a000-45eb-b653-5c6ead4bb349)

![image](https://github.com/user-attachments/assets/6b41a7d9-3169-4e5e-a37f-daf1f1347b33)

The tiles for each floor (Ground set as the background, Floor 2 handled by Levels) are made correctly with alpha channel "holes" for where the stairs up to each location are. I've been making maps for use with Levels for years now, so I know I'm doing that part correctly. 

Anyway, if there's any fix for this or troubleshooting I could do, let me know. I know you just updated the Terrain Mapper module for the stairs function, but I want to use ramps for the stairs, not the instant teleportation of a token from ground to floor 2 when they touch a stair, mostly because I have larger castle maps with long stairs where fighting on them will take place.

**Comment by Commander-Fayne** [comment]
Update: Turned on the stairs region behavior, and going up is the same, but going down is even worse. See gif

![Ramp down missing2](https://github.com/user-attachments/assets/90222feb-a653-4271-99ac-6ba776e3c4d2)

Here is the region behavior
![image](https://github.com/user-attachments/assets/67522acd-85a3-4a1b-9e19-674b43a1d92f)

**Comment by caewok** [comment]
If you have defined a ramp for those stairs, I don't see why you would also add a stairs behavior. The ramp can take you from 0 to 10 feet on its own, in a diagonal down/up movement. The stairs will move you straight up/down. You should just pick one.

As for Levels, it is complaining that (likely either option) is taking the token from 10 feet to 0 feet, which means it moves through the floor. Of course, that is what you want it to do, because with either a ramp or the stairs behavior, the token is supposed to move from one floor to another. Is there a setting in Levels (maybe specific to that floor?) that you can set so it stops complaining when the token moves between floors? That "error" is a Levels error that has nothing to do with Terrain Mapper.

**Comment by Commander-Fayne** [comment]
Ah I see. I thought you had to pair the region behavior with the Terrain Mapper ramp behavior. After reaching out to TheRipper93 on his discord, he says there isn't a way to disable that warning, which is incredibly frustrating, especially when moving a handful of tokens at a time. What a bummer. 

After updating Terrain Mapper to 0.4.1 and Elevation Ruler to 0.10.4, I'm noticing some new issues. Let me know if I should make a new post for this. 

![Cannot move token](https://github.com/user-attachments/assets/d663df8f-dc62-4dc5-bba5-883e9735c072)


First, when I load up the map, I can't move my tokens sometimes. This is the error that comes out when I try to. 

![image](https://github.com/user-attachments/assets/7248939b-1c58-4f42-9eed-4be9da19c17c)

The token can be selected, but when I try to drag the token, either it doesn't move at all and Foundry defaults to thinking I'm just clicking and holding for a ping OR the token can be moved, but when I set it down, it doesn't actually move, with Foundry thinking I canceled the move and putting the token back where it was. 

These errors pop up as well when this happens

![image](https://github.com/user-attachments/assets/1c6565b1-8b2c-4e47-9537-7ac216ac3583)

![image](https://github.com/user-attachments/assets/0922069b-8e56-4c31-84d7-91fe0431490b)

![image](https://github.com/user-attachments/assets/f043e525-1fb4-424a-b946-bc59ef90fff7)

**Comment by Commander-Fayne** [comment]
Note: Updated to 0.10.5 and 0.4.2 and that seemed to fix the issue.

**Comment by Commander-Fayne** [comment]
So, the only other thing that's happening is a very weird transition between ramps. Demonstrated here. It seems like the end of the ramp drops the token off its ramp to the floor (in this case, floor 3, at 30 ft), then the next ramp picks the token up, raising them back to the top of the ramp before it lets the token continue onward. The end result is the same, but the actor gets a peek under the ramp briefly, which could spoil some hidden things. 

![Token Ramp Jumping](https://github.com/user-attachments/assets/7cdb6361-c993-4282-ae1e-a8fafb693174)

**Comment by caewok** [comment]
> Ah I see. I thought you had to pair the region behavior with the Terrain Mapper ramp behavior. After reaching out to TheRipper93 on his discord, he says there isn't a way to disable that warning, which is incredibly frustrating, especially when moving a handful of tokens at a time. What a bummer.

Yes, perhaps that is something TheRipper93 could add. Or at least add some sort of API so that I could signal to Levels to ignore that particular movement. The error is definitely created by Levels; I don't believe Foundry does any check like that based on elevation.

**Comment by caewok** [comment]
Thanks for the feedback! I added your last point about the ramps as a new issue to investigate.
