### ISSUE TITLE
ActiveEffect status conditions from terrains not applied

### ISSUE THREAD

**Issue by nphyx** [caewok/fvtt-terrain-mapper#45]
# STR

1.  create a new terrain
2.  in details tab -> status conditions, select any status condition
3.  submit changes
4.  configure region -> behaviors tab -> add behavior
5.  select "set terrain" option
6. click "create new region behavior"
7. in dialog -> set terrain -> terrains, select created terrain created above
8. save
9. on canvas, select a token and move it into the affected region

# Expected:

Status condition should be applied to token, along with any other ActiveEffect changes.

# Actual:

Status condition is not applied.

See also:
`game.actors.get(<tokenActorId>).statuses` => status condition not present

# Additional Info:

This occurs in a homebrew system I'm working on, which is not publicly available, so I don't know if it would be reproducable in e.g. dnd5e or swade. But you should be able to reproduce it in a barebones system, e.g. one created by https://github.com/asacolips-projects/boilerplate.

Seems this is caused by `unique_effects/UniqueActiveEffect.js`, in `_addToToken`, `_addToTokenLocally`: the status conditions from the ActiveEffect are not transferred, and are instead overridden by the `ActiveEffect.img` if "Status Icon" option was ticked in the terrain's ActiveEffect config.

I have made a hacky fix around line 64, pulling in status conditions from the original effect:

```js
        const datum = { statuses: [...e.document.statuses] || [] };
```
also at line 89:

```js
        && effect.displayStatusIcon )  doc.statuses = [...(doc.statuses || []), effect.img];
``` 

This seems to have fixed the problem. I can submit a pull request for these changes if you like, but I'm not sure it's the best solution.

**Comment by caewok** [comment]
Thanks! No need for the PR, as I was looking at this issue while investigating compatibility with a5e. Newly released v0.4.3 addresses this in two ways: 

1. No longer obliterates the statuses from the underlying AE. I thought `foundry.utils.mergeObject` would merge the arrays, but it was not. 
2. Hooks AE creation and deletion to add the associated effects for each status. This gets a bit complicated, but in default Foundry and systems like dnd5e or a5e, if you define an AE with 1+ statuses (conditions), adding the AE adds the statuses to the token's actor but does not toggle on the associated conditions. As a result, they don't show up in the token HUD or the actor sheet. In my opinion, this is really confusing. So the hooks I added will create the necessary active effects for each status added by the new AE, along with some logic to attempt to avoid duplicates and to only remove them if no other AE is adding them.
