### ISSUE TITLE
Recently created ramp polygon in a region sets all previous polygons within region as plateau behavior

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-terrain-mapper#48]
When using a single region to make several ramps, only the most recent ramp is functioning properly. [EDIT: I discovered this has to do with the region closest to the center of the map works normally, not the region most recently created] On this map, the roofs all have East facing ramps for the west facing roofs, meaning as I understand this module, the base of the ramp is furthest west, and the top is furthest east. 

When making this map, I have one region for that ramp. Floor 3 Roof East. There are several polygons within this region for each west facing roof.

![image](https://github.com/user-attachments/assets/b95c30a3-ed02-4e38-b02c-54b4e80ebc49)

However, all these roof region polygons are acting like plateaus, where the token remains at the top elevation and does not go up or down the ramp. The East Ramp roof is set up without any region behavior, and in the Terrain Mapper tab is set to ramps like this. 

![image](https://github.com/user-attachments/assets/1aec0b36-9eda-4a1b-b693-5a6997f46ffb)

They were acting as ramps until I started making several of them throughout the map. Currently, only the most recently created roof is acting like a ramp. In these gifs, the first token is moving on the most recently created ramp. It works as intended. The second token is north of this ramp, where the region overlaps longitude with the first. The third token is moving on a ramp far away from the first two, to demonstrate it is not functioning at all. And again, the module does seem to be taking control of token elevation, it just seems to be treating all previously created ramps as plateaus or not at all.

![Ramps functioning incorrectly1](https://github.com/user-attachments/assets/c598cd1d-c365-46ab-bfb1-4bb7d8600b03)

![Ramps functioning incorrectly2](https://github.com/user-attachments/assets/54066480-c246-4ba6-acb4-8f0f6f434e0a)

![Ramps functioning incorrectly3](https://github.com/user-attachments/assets/2ab4e6fb-d7c3-4162-9cee-3ed2ec64b1b4)

**Comment by Commander-Fayne** [comment]
In this gif, I've made an entirely new region. Its elevation is 0/10'. The region is set to ramp, with plateau elevation at 10', lowest ramp at 0', and the ramp facing east, or 270 according to your documentation.

![image](https://github.com/user-attachments/assets/5fe4b6fd-0a28-488d-87f9-5ad33858e461)

I made three polygons in a row, starting with the most west. If I make just one polygon, the ramp functions correctly. If I make several, (in this case, first was west, second was center, third was right) the ramp behavior breaks. In this example, the second one functions normally, the first doesn't function at all, and the third acts like a plateau. These are all polygons in the same region which should all be acting like ramps. 

![image](https://github.com/user-attachments/assets/ed03513b-28fa-4f03-9166-e15d2543cef3)
![Ramps functioning incorrectly4](https://github.com/user-attachments/assets/ed47fb01-6fac-4428-9c2b-75921d67fe41)

**Comment by Commander-Fayne** [comment]
New region, same settings. All polygons west of the token do not function at all. The polygon immediately east of the token works normally, and all polygons beyond that function like plateaus. I created them in order from east to west. 

Actually, something that might be super useful! The token is standing on the center of the map. Maybe it has something to do with that? The ramp nearest to his east works normally, and is the closest ramp to the center of the map. Beyond that, they all function like plateaus, and all ramps to his west don't work at all. That's got to be important!

**Comment by Commander-Fayne** [comment]
Yes! After changing the ramp orientation to face west, the first ramp west of the center of the map works normally. The ramps beyond that work like plateaus, and all ramps to the east of center of the map don't work at all.

**Comment by caewok** [comment]
There are at least two things going on here. 
1. You probably don't want to define multiple polygons for a single ramp. All the polygons for a region are considered on ramp, so the border of all the polygons will define the elevation steps for the ramp. You may want multiple polygons if you have holes in the ramp. But if you have multiple "roofs" and you want each roof to go from 20 feet to 30 feet, you will need multiple regions. 
2. There is definitely a bug when measuring the ramp dimensions for multiple regions. It is not getting the math right .

**Comment by caewok** [comment]
Okay, so in v0.4.4, I made several changes that should address this. I fixed the bug about measuring ramp dimensions with multiple polygons. And you should see a new config checkbox in the Terrain Mapper region tab to treat polygons separately for ramps.

This gives you two options: 
1. Treat the entire region as one ramp. Good when you have a weird shape created by combining multiple polys or if you have holes. 
2. Treat each non-hole poly as a separate ramp. Good when you have a bunch of roofs like in the screenshots you provided, where each is at the same bottom and top elevation. This should probably handle holes okay, but if you start overlapping non-hole polygons, it could get weird.

**Comment by Commander-Fayne** [comment]
Absolutely perfect. All issues I had with Terrain Mapper and Elevation Ruler are fixed as of your update. You are an angel!
