### ISSUE TITLE
Getting this red error when trying to load terrainmapper in pf2e

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-terrain-mapper#51]
![image](https://github.com/user-attachments/assets/1443fa59-9c3c-4c41-b261-9fca23ed5f0f)

I hadn't noticed until it caused issues with elevation ruler. I disabled all modules but libwrapper, terrainmapper and modulemanagement+ and the error still occurs on load.

**Comment by caewok** [comment]
Terrain Mapper is now at v0.4.4, so I recommend updating.
