### ISSUE TITLE
Players cannot move tokens

### ISSUE THREAD

**Issue by Eternalserb024** [caewok/fvtt-terrain-mapper#52]
I am having an issue where anytime a player attempts to move a token, the message "You cannot take this action while the token object is locked." pops up on screen. A projection of the token is moved to the new location but the original token is locked in place.
![Screenshot 2024-09-04 154926](https://github.com/user-attachments/assets/474b81c6-f8c2-40a4-bb19-ebe0286d8d94)

**Comment by caewok** [comment]
Does this happen when only Terrain Mapper and libWrapper are active modules?

**Comment by Eternalserb024** [comment]
yes, I disabled all other modules to test it and the issue was still present.

**Comment by caewok** [comment]
Does it still throw an error in v0.4.5?

**Comment by Eternalserb024** [comment]
No error anymore, issue resolved

**Comment by Numnzel** [comment]
I'm actually experiencing this problem in Foundry V12 Stable Build 331.

With only Terrain Mapper and libWrapper enabled and no regions set, when a player moves the token unto a wall the token now gets stuck and as a GM I have to unstuck it manually.

This does not happen when I disable Terrain Mapper.
