### ISSUE TITLE
Performance drop when dragging tokens over a region with Difficult terrain using Elevation Ruler

### ISSUE THREAD

**Issue by SilvesTheRog** [caewok/fvtt-terrain-mapper#58]
Hello!
I've just installed the module and my dependencies are up-to-date, but when I try to drag a token over a region with difficult terrain, FoundryVTT starts lagging heavily. My CPU is AMD Ryzen 7 5800X, if it matters.

Here's a demonstration of the issue: https://youtu.be/2Xe7t13VOJs

Also, when a token enters the region, there's a warning in the console as well:

![image](https://github.com/user-attachments/assets/3a7d7eaa-8269-4036-856c-39d54ca87eac)

**Comment by SilvesTheRog** [comment]
UPD: Turns out it happens with Elevation Ruler enabled, specifically when "Use Token Ruler" setting is active.

**Comment by caewok** [comment]
Addressed in v0.4.6 and Elevation Ruler v0.10.11. Should be much faster now. The slowdown was when ER asked TM for the move penalty through a region. To do that, TM was cloning an actor to determine what active effects would be imposed, but it took way too long for Foundry to initialize and update the actor.
