### ISSUE TITLE
Token Ramp Problems

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-terrain-mapper#61]
Updated elevation ruler to 0.10.11 and Terrain Mapper to 0.4.6

With pathfinding on, it no longer sees the ramp I've made. I have to waypoint the token to the base of the stairs for it to start changing elevation as I drag the token along the ramp. Additionally, sometimes it rockets the token to -50000 elevation, then brings it back up to the elevation it started at. 

Region of the polygon in question

![image](https://github.com/user-attachments/assets/4674fc88-de25-465d-bdcb-8f8b8170e1a7)

And here is the behavior
![Down to Hell](https://github.com/user-attachments/assets/7873adb1-b888-4277-9e89-f2c364a439b4)

If I waypoint or stop the token on the ramp, it will change elevation correctly as long as I stop the token somewhere else on the ramp, but will not change elevation if it leaves the ramp on the higher end. 

![Finicky but works](https://github.com/user-attachments/assets/1a282836-b115-4c1c-9776-31168c4df97a)

And if I start at the top on the second level and move the token down the ramp to the floor, it sets elevation to 0, moves them across the ramp, then sets elevation to -50000, returns to 10, then stops. 

![Finicky but works2](https://github.com/user-attachments/assets/6b16188b-debf-44ff-b644-16324e6ae5db)

**Comment by Commander-Fayne** [comment]
Ignore the token vision not updating when they transition levels. That's a known Levels bug that hasn't been addressed yet.

**Comment by CyantoIogy** [comment]
I'm having this issue more or less. If I have Levels enabled, I don't see the height change. If I disable it, I see the drop to -50000. I did some testing while elevation ruler was enabled to see if my height changes. If I have the default height of 0, nothing happens. If I set my token height to 1, I can see the elevation change in 1ft increments while going up a slope, however, it doesn't represent the slope height I set. For example, if I set token height to 1, at the top of a 15 foot slope, the height is 5. If I change the step height, I get different results, but a step of 0 shows negative heights when I'm pathing through the area.
![image](https://github.com/user-attachments/assets/415df207-0c16-47d8-94e1-0f15a35219c2)
I also don't see the elevations unless I'm gridless. If I turn the grid back on, I don't see any elevation changes at all. I've tested this with Levels and Wall Height enabled and disabled. It doesn't make a difference.

I tested a new region on a different map and drew a simple square...everything is working correctly.

**Comment by CyantoIogy** [comment]
Update: I removed the old regions and redrew them with simpler wall designs, and they're working so far. Going to test a complicated drawing again and see if that's the issue.

**Comment by CyantoIogy** [comment]
Update 2: redrawing the regions and/or walls seems to resolve the issue. Complexity of the wall design didn't matter. Switched to a different scene that already had ramps/plateaus and redrawing worked to fix the issue there as well. No idea what caused the behavior. I couldn't trigger a visible error in the console.

**Comment by caewok** [comment]
The dropping to large negative elevations should be addressed in v0.4.9.
