### ISSUE TITLE
Plateau Mesa Teleport not setting correct height

### ISSUE THREAD

**Issue by KLSteinwand** [caewok/fvtt-terrain-mapper#63]
Foundry Version: 12.331
PF2e Version: 6.4.1
Terrain Mapper Version: 0.4.6

The issue that is occurring is that when a token is being teleported via the default Region Teleport behavior onto a Plateau Mesa, it's not setting to the correct elevation. Even when the region surrounding that region marked for the teleport landing is set to what the elevation should be, it will not set. And once entering a separate teleporting region to go to a different elevation, it completely ignores what that elevation should be, and instead adds to the token's elevation in a fractionalized amount. For example 0 to 20 feet over the course of a 4 square plateau ramp will set to 15.5 feet when set to a plateau mesa of 20 feet, and a plateau ramp meant to go from 20 to 0 feet over the course of 4 squares will not affect the elevation, and then once teleported the new elevation will be 16.75 feet, then 17.375 attempting to go to 20 feet, and then 17.7 feet attempting to go back to 20 feet.

Attempting to go from a higher plateau mesa to a plateau ramp that decreases elevation however to see if the opposite affect occurs in teleportation however is bringing back an issue similar to #57 that I had opened (and posted an update on after it was closed) in which it will not lower a token's elevation even if both the plateau mesa and plateau ramp are both set to positive integers.

**Comment by caewok** [comment]
Added handling of teleporting tokens in v0.4.9.
