### ISSUE TITLE
Elevation not displaying above token

### ISSUE THREAD

**Issue by Jnov36** [caewok/fvtt-terrain-mapper#68]
As the title says.  I get a an icon that is an exclamation point in a triangle above the token.  I'm using the latest foundry version.  I'm thinking I have something incorrect and not a module issue.  Thanks.

**Comment by Jnov36** [comment]
The module Stairway (Teleporter) seems to cause the problem.  I'm searching for an alternative.

**Comment by caewok** [comment]
I am not seeing any exclamation point in a triangle or anything wrong when I try to use Stairways with Terrain Mapper. Closing for now as not replicated but feel free to open a new issue with more details (system, active modules, any errors in console).
