### ISSUE TITLE
Drag Ruler: fix coloration of the ruler so it keeps the green and yellow portions

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-terrain-mapper#8]
https://ptb.discord.com/channels/915186263609454632/1161759359089520690/1163520518582980698

**Comment by Peach774** [comment]
> https://ptb.discord.com/channels/915186263609454632/1161759359089520690/1163520518582980698

This doesn't work - you might want to download an image and post that or something.

**Comment by caewok** [comment]
Closing as I don't see Drag Ruler getting updated anytime soon. Recommend that anyone interested in token speed highlighting try my Elevation Ruler module instead.
